services:
  - type: web
    name: anwer-telegram
    env: python
    region: frankfurt
    plan: free
    branch: render-deploy
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PORT
        value: "10000"
      - key: SESSION_SECRET
        generateValue: true
